name       : haskell-hpack
version    : 0.28.2
release    : 3
source     :
    - http://hackage.haskell.org/package/hpack-0.28.2/hpack-0.28.2.tar.gz : b9601332bbac2f042947be1f7478ed0c72367e4caa211b779a75dc26cd8180a3
license    : MIT
component  : programming.haskell
summary    : An alternative format for Haskell packages
description: |
    An alternative format for Haskell packages
builddeps  :
    - haskell-bifunctors
    - haskell-cabal-install
    - haskell-http-client-tls
    - haskell-glob
    - haskell-yaml
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
