name       : haskell-hpack
version    : 0.31.2
release    : 4
source     :
    - https://hackage.haskell.org/package/hpack-0.31.2/hpack-0.31.2.tar.gz : 6f00834e99463f022fe9346b9c2cdb1054a6d89e9d6b70a4869c2b5a50304dd0
license    : MIT
component  : programming.haskell
summary    : An alternative format for Haskell packages
description: |
    An alternative format for Haskell packages
builddeps  :
    - haskell-bifunctors-devel
    - haskell-cabal-install
    - haskell-glob-devel
    - haskell-http-client-tls-devel
    - haskell-infer-license-devel
    - haskell-yaml-devel
rundeps    :
    - devel:
        - haskell-bifunctors-devel
        - haskell-glob-devel
        - haskell-http-client-tls-devel
        - haskell-infer-license-devel
        - haskell-yaml-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
